Sara
saracruzfdez/dvdStoreSprinBootJPA pull request #1
Opened 2023-09-19 12:47 UTC by saracruzfdez

2023-09-22 14:27 UTC, Mekouar-Ayoub approved these changes

2023-09-22 14:30 UTC, Mekouar-Ayoub requested changes

2023-09-22 14:30 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvdstore/controllers/ClientDTO.java
> +public class ClientDTO {
Créer une nouveau DTO qui prend en compte l'id et l'utiliser dans le getAll et getByid

2023-09-22 14:30 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvdstore/controllers/DvdDTO.java
>  }
Créer un dto qui prend en compte l'id et l'utiliser dans getAll et getById

2023-09-22 14:30 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvdstore/services/ClientServiceModel.java
> +public class ClientServiceModel {
ajoute l'id en optional

2023-09-22 14:30 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvdstore/services/DvdServiceModel.java
>      private String name;
ajoute id en optional

2023-09-22 14:34 UTC, Mekouar-Ayoub requested changes

2023-09-22 14:34 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvdstore/controllers/VenteController.java
> +    public boolean addVenteToStore(@RequestBody VenteDTO venteDTO){
Date doit arriver dans le DTO

2023-09-22 14:34 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvdstore/controllers/VenteDTO.java
> +public record VenteDTO(Long client_id, Long dvd_id, int quantity) {
Ajoute la date

2023-09-22 14:34 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvdstore/services/VenteService.java
> +        VenteRepositoryModel venteRepositoryModel = new VenteRepositoryModel(clientRepositoryModel, dvdRepositoryModel, venteServiceModel.getQuantity());
tu dois calculer le prix dans le constructeur

2023-09-22 14:34 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvdstore/repositories/VenteRepositoryModel.java
> +        this.clientRepositoryModel = clientRepositoryModel;
this.total = quantity * dvdRepositoryModel.getPrix()
quelque chose de ce genre là

2023-10-16 20:38 UTC, closed without merging

2023-10-16 20:38 UTC, saracruzfdez commented
Je ferme cette PR car elle n'est plus utile, a la place, il faut regarder https://github.com/saracruzfdez/dvdStoreSprinBootJPA/pull/4