Feat/ionic
saracruzfdez/dvdStoreSprinBootJPA pull request #6
Opened 2023-10-27 13:24 UTC by saracruzfdez

Nouvelle branche contenant la partie ionic. Tu trouves également la partie ionic sur la branche feat/Panier (je me suis trompée, car j'ai travaillé ionic et push sur Feat/Panier)

2023-11-08 09:15 UTC, Mekouar-Ayoub requested changes

2023-11-08 09:15 UTC, Mekouar-Ayoub commented on dvdstore/src/app/app.component.html
> +    <div style="margin-top:10%;">
à eviter absolument cree une classe css

2023-11-08 09:15 UTC, Mekouar-Ayoub commented on dvdstore/src/app/dvds/dvds.component.html
> +        <div *ngFor="let dvdmodel of dvds" class="card text-center m-2">
FIltrer par categorie

2023-11-08 09:15 UTC, Mekouar-Ayoub commented on dvdstore/src/app/inscription-form/inscription-form.component.html
> +Login name                </label>
soit email, soit téléphone

2023-11-08 09:15 UTC, Mekouar-Ayoub commented on dvdstore/src/app/login-form/login-form.component.html
> +Login name                </label>
la misma acqui

2023-11-08 09:15 UTC, Mekouar-Ayoub commented on dvdstore/src/app/services/authentication.service.ts
> +  is_auth = (): boolean => {
mieux vaut tester sur user + token

2023-11-08 09:15 UTC, Mekouar-Ayoub commented on dvdstore/src/app/services/clients.service.ts
> +  return this.http.get('http://localhost:9000/clients', { headers: this.getHeaders() }) as Observable<Array<Client>>;
Il y a une solution pour mettre les headers automatiquement à toutes les requetes mais c pas grave laisse comme ça

2023-11-08 09:21 UTC, Mekouar-Ayoub requested changes

2023-11-08 09:21 UTC, Mekouar-Ayoub commented on dvdstore_back2/pom.xml
> +        <dependency>
tu l'utilise vraiment ?

2023-11-08 09:21 UTC, Mekouar-Ayoub commented on dvdstore_back2/src/main/java/com/simplon/dvdstore_back2/controllers/PanierController.java
> +@CrossOrigin(origins = "http://localhost:9000")
Mieux vaut avoir un mvc configurer dans ta classe application mais laise comme ça

2023-11-08 09:21 UTC, Mekouar-Ayoub commented on dvdstore_back2/src/main/resources/application.properties
>  spring.datasource.username=postgres
comment tu peux faire en sorte que ces informations confidentielles ne soient pas partagées dans git

2023-11-08 09:21 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvdstore/controllers/FeignClientController.java
> +@CrossOrigin("*")
Non !

2023-11-08 09:21 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvdstore/feign/FeignClientProxy.java
> +package com.simplon.dvdstore.feign;
Mieux vaut que tu ai un service entre Controller et Proxy et d'ailleurs Proxy doit s'appeller Repository

2023-11-08 09:21 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvdstore/controllers/FeignClientDTO.java
> +public class FeignClientDTO {
Mieux vaut que tu ai plusieurs DTO un pour chaque route ça t'évitera de renvoi plusieurs fois la meem donnée dans tes routes (getbyid, updatebyid ...) mais laisse comme ça

2023-11-13 08:10 UTC, saracruzfdez commented on dvdstore/src/app/app.component.html
> +    <div style="margin-top:10%;">
ok, c'est noté

2023-11-13 08:11 UTC, saracruzfdez commented on dvdstore/src/app/dvds/dvds.component.html
> +        <div *ngFor="let dvdmodel of dvds" class="card text-center m-2">
ok, je note ça

2023-11-13 08:11 UTC, saracruzfdez commented on dvdstore/src/app/inscription-form/inscription-form.component.html
> +Login name                </label>
ok

2023-11-13 08:12 UTC, saracruzfdez commented on dvdstore/src/app/login-form/login-form.component.html
> +Login name                </label>
ok

2023-11-13 08:12 UTC, saracruzfdez commented on dvdstore/src/app/services/authentication.service.ts
> +  is_auth = (): boolean => {
d'accord

2023-11-13 08:12 UTC, saracruzfdez commented on dvdstore/src/app/services/clients.service.ts
> +  return this.http.get('http://localhost:9000/clients', { headers: this.getHeaders() }) as Observable<Array<Client>>;
Très bien

2023-11-13 08:12 UTC, saracruzfdez commented on dvdstore_back2/pom.xml
> +        <dependency>
peut-être pas...

2023-11-13 08:12 UTC, saracruzfdez commented on dvdstore_back2/src/main/java/com/simplon/dvdstore_back2/controllers/PanierController.java
> +@CrossOrigin(origins = "http://localhost:9000")
ok

2023-11-13 08:13 UTC, saracruzfdez commented on dvdstore_back2/src/main/resources/application.properties
>  spring.datasource.username=postgres
ne pas les mettre dans mon commit et partager autrement, mais comment ?

2023-11-13 08:13 UTC, saracruzfdez commented on src/main/java/com/simplon/dvdstore/controllers/FeignClientController.java
> +@CrossOrigin("*")
ok

2023-11-13 08:13 UTC, saracruzfdez commented on src/main/java/com/simplon/dvdstore/feign/FeignClientProxy.java
> +package com.simplon.dvdstore.feign;
ok

2023-11-13 08:14 UTC, saracruzfdez commented on src/main/java/com/simplon/dvdstore/controllers/FeignClientDTO.java
> +public class FeignClientDTO {
ok

2023-11-13 08:25 UTC, Mekouar-Ayoub approved these changes

2023-11-13 08:25 UTC, merged